### ISSUE TITLE
Feature Request: allow `@combine` to accept functions

### ISSUE THREAD

**Issue by xiaodaigh** [jkrumbiegel/DFMacros.jl#10]
`combine(groupby(df, :grp), nrow)` works in DataFrames.jl

 but 

`@combine(groupby(df, :grp), nrow)` doesn't produce the right output in DataFrameMacros.jl

**Comment by jkrumbiegel** [comment]
this now exists as `@combine(..., @nrow)` so it doesn't interfere with other syntax https://github.com/jkrumbiegel/DataFrameMacros.jl/pull/25
